import {photoLanguageToggle,photoAttributes} from './photography.mjs';
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bi = (zh,en) => `<span data-photo-lang="zh" lang="zh-Hant">${esc(zh)}</span><span data-photo-lang="en" lang="en">${esc(en)}</span>`;
const place = v => bi(`${v.venue} · ${v.city.zh}`,`${v.venue} · ${v.city.en}`);
const exhibitions = v => v.exhibitions.length ? `<p class="exhibition-list-label">${bi('展覽包括','Exhibitions include')}</p><ul class="visit-exhibition-list">${v.exhibitions.map(e=>`<li>${e.url?`<a href="${esc(e.url)}">`:''}${bi(e.zh,e.en)}${e.url?'</a>':''}</li>`).join('')}</ul>` : '';
const heading = (titleZh,titleEn,back,backZh,backEn,icon) => `<header class="exhibition-heading"><a class="back" href="${back}">${icon('arrow')}${bi(backZh,backEn)}</a><div class="photo-heading-row"><h1>${bi(titleZh,titleEn)}</h1>${photoLanguageToggle()}</div></header>`;
export function renderExhibitions(visits,icon) {
 return `<section class="exhibitions-page" data-photo-region data-lang="zh" lang="zh-Hant">${heading('看展','Exhibitions','../','學術主頁','Academic homepage',icon)}<div class="exhibition-catalogue">${visits.map((v,i)=>`<article class="exhibition-entry"><a class="exhibition-cover" href="./${esc(v.id)}/"><img src="../${v.preview.src}" width="${v.preview.width}" height="${v.preview.height}" alt="${esc(v.photos[0].altZh)}" ${i?'loading="lazy"':'fetchpriority="high"'}></a><div class="exhibition-entry-copy"><span class="exhibition-number" aria-hidden="true">${String(visits.length-i).padStart(2,'0')}</span><time datetime="${v.date}">${v.date.replaceAll('-','.')}</time><h2><a href="./${esc(v.id)}/">${place(v)}</a></h2>${exhibitions(v)}<a class="visit-open" href="./${esc(v.id)}/">${bi('進入展廳','View gallery')}${icon('arrow')}</a></div></article>`).join('')}</div></section>`;
}
export function renderVisit(v,icon) {
 return `<section class="exhibitions-page exhibition-visit" data-photo-region data-lang="zh" lang="zh-Hant">${heading(`${v.venue} · ${v.city.zh}`,`${v.venue} · ${v.city.en}`,'../','所有看展紀錄','All visits',icon)}<div class="visit-information"><time datetime="${v.date}">${v.date.replaceAll('-','.')}</time>${exhibitions(v)}<p class="preview-hint">${bi('點開照片，放大觀看。','Click a photograph for a closer look.')}</p></div><div class="exhibition-wall">${v.photos.map((p,i)=>{
 const attrs=photoAttributes({...p,title:p.artwork?.en||`${v.venue} · ${String(i+1).padStart(2,'0')}`,titleZh:p.artwork?.zh||`${v.venue} · ${String(i+1).padStart(2,'0')}`,location:`${v.venue}, ${v.city.en}`,locationZh:`${v.city.zh} ${v.venue}`,date:v.date.slice(0,7),caption:'',note:''});
 return `<figure><a class="exhibition-image" href="../../${p.src}" data-figure data-album="${v.id}" ${attrs}><img src="../../${p.src}" width="${p.width}" height="${p.height}" alt="${esc(p.altZh)}" ${i<2?'':'loading="lazy"'} decoding="async"></a><figcaption><span class="exhibition-number">${String(i+1).padStart(2,'0')}</span>${p.artwork?`<span>${bi(p.artwork.zh,p.artwork.en)}<a class="artwork-source" href="${esc(p.artwork.source)}">${bi('作品資料 ↗','Artwork details ↗')}</a></span>`:''}</figcaption></figure>`;
 }).join('')}</div><a class="visit-return" href="../">${bi('返回看展目錄','Back to exhibitions')}${icon('arrow')}</a></section>`;
}
